#!/bin/sh

# Set path to where session file exists
session_path=/tmp/session

# If the session file does not exist, create it
[ ! -f "$session_path" ] && bw unlock | grep "export BW_SESSION" | cut -d'"' -f 2 > ${session_path}

# Load the session file
session=`cat $session_path`

# Parse out the item names
list=$(bw list items --session "${session}" --pretty | grep -w name | cut -c14- | sed 's/"//' | sed 's/,//' )

# Get selection
selection=$(echo "$list" | dmenu)

# Return the username and password
bw --session $session get username $selection
bw --session $session get password $selection
