#!/bin/sh

# Auto Monitor Switcher
# Author: Alexander Brown
# v3
# Change Log:
# v2.0: Using grep -w to simplify script
# v2.1: Monitors that are not connected are turned off
# v3  : Set up for Pooter

#################################################################################
# Pooter
#################################################################################
P="DP-3"
L="DVI-D-1"
R="DP-2"
O1="DP-2"
O2="HDMI-A-0"

case "$1" in
    game)
        xrandr | grep -w "$L connected" && xrandr | grep -w "$P connected" && \
            xrandr | grep -w "$R connected" && \
            xrandr --output $O1 --off --output $O2 --off  --output $L --off\
                   --output $P --primary --mode 2560x1080 --rate 60.00 --rotate normal \
                   --output $R --mode 1600x900  --rotate left --right-of $P && echo "Pooter Game"
        ;;
    *)
        xrandr | grep -w "$L connected" && xrandr | grep -w "$P connected" && xrandr | grep -w "$R connected" && \
            xrandr --output $O1 --off --output $O2 --off \
                   --output $P --primary --mode 3440x1440 --rate 144.00 --rotate normal \
                   --output $R --mode 1600x900  --rotate left --right-of $P \
                   --output $L --mode 1600x900  --rotate left --left-of $P && echo "Pooter"
        ;;
esac
