#!/bin/sh

# Auto Monitor Switcher
# Author: Alexander Brown
# v1.0

# No external display present 
xrandr | grep -w 'DP1 disconnected' && xrandr | grep -w 'HDMI1 disconnected' && xrandr | grep -w 'HDMI2 disconnected' && xrandr --output eDP1 --auto --primary && echo "eDP1"

# Display port connected (Display only on external monitor)
xrandr | grep -w 'DP1 connected' && xrandr --output eDP1 --off --output DP1 --auto --primary && echo "DP1"

