#!/bin/sh

if [ "$#" -ge 2 ]
then
	ls | while read -r FILE
	do
	    mv -v "$FILE" `echo $FILE | tr "$1" "$2"`
	done
else 
	echo "ERROR: Invalid arguments"
	echo "\$1 - Character to be replaced"
	echo "\$2 - Character to replace with"
fi 
