#!/bin/bash
# ========================================================================
#       Converts VimWiki formatted markdown to Github markdown
# ========================================================================
# adapted from this script:
#   https://gist.github.com/hotoo/9866720
# must use gnused because of here-document
# watch out for the spaces and tabs with here-documents
#   https://unix.stackexchange.com/questions/76481/
#
# usage:
#
# vw2md.sh  [fileglob, e.g., wikidir/subdir/*.txt]
#
#   input can have any extension, .txt, .wiki, .markdown
#   output will be given .md extension (can be changed: $oext)

oext='md'
for infile in $@; do
  [ -e "$infile" ] || continue
  ext="${infile##*.}"
  base=$(basename "$infile" "$ext")
  dir=$(dirname "$infile")
  outfile="$dir"/"$base""$oext"
  #echo  infile "$infile"
  #echo base "$base"
  #echo dir "$dir"
  echo outfile "$outfile"
  if [ ! -f "$outfile" ]
  then
    sed -f - "$infile" > "$outfile" <<- '      SED_SCRIPT'
      s/# \(.*\)$/* \1/g
      s/^= \(.*\) =$/# \1/g
      s/^== \(.*\) ==$/## \1/g
      s/^=== \(.*\) ===$/### \1/g
      s/^==== \(.*\) ====$/#### \1/g
      s/^===== \(.*\) =====$/##### \1/g
      s/^====== \(.*\) ======$/###### \1/g
      s/{{{class="brush: *\([^"]*\)"/\`\`\`\1/g
      s/{{{class="\([^"]*\)"/\`\`\`\1/g
      s/{{{/\`\`\`/g
      s/}}}/\`\`\`/g
      s/\[\([^] ]\{1,\}\)\]\([^](]\)/![pic](\1)\2/g
      s/\[\([^] ]\{1,\}\)\]$/![pic](\1)/g
      s/\[\[\(\([^|]\{1,\}\)\|\)\([^]]\{1,\}\)\]\]/[\3](\2.md)/g
      s/\[\[\([^]]\{1,\}\)\]\]/[\1](\1.md)/g
      s/\[\(https\{0,1\}:\/\/[^ ]*\) \([^]]*\)\]/[\2](\1)/g
      s/%% \(.*\)/<!-- \1 -->/g
      /%toc.*/d
      s/%title \(.*\)/# \1/g
      s/%nohtml/- status: draft/g
      SED_SCRIPT
    echo "CONVERTED:  $outfile"
  else
    echo "skipped:    $outfile"
  fi
done
