#!/bin/sh

path=~/NextCloud/Documents/library
books=$(ls $path/*)
b=$(echo "$(basename -a $books)" | dmenu -l 20 -p "Book: ")
reader="emacs"

# Open book in PDF reader
[ ! -z "${b}" ] && $reader "$path/$b"
